In [14]:
import pandas as pd

In [15]:
url = "https://happiness-report.s3.us-east-1.amazonaws.com/2025/Data+for+Figure+2.1+(2011%E2%80%932024).xlsx"

In [16]:
df = pd.read_excel(url)

In [17]:
whr_24 = df[df["Year"] == 2024]

whr_24

,Year,Rank,Country name,Ladder score,upperwhisker,lowerwhisker,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,2024,1,Finland,7.736,7.810,7.662,1.749,1.783,0.824,0.986,0.110,0.502,1.782
13,2024,2,Denmark,7.521,7.611,7.431,1.825,1.748,0.820,0.955,0.150,0.488,1.535
26,2024,3,Iceland,7.515,7.606,7.425,1.799,1.840,0.873,0.971,0.201,0.173,1.659
45,2024,4,Sweden,7.345,7.427,7.262,1.783,1.698,0.889,0.952,0.170,0.467,1.385
58,2024,5,Netherlands,7.306,7.372,7.240,1.822,1.667,0.844,0.860,0.186,0.344,1.583
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1905,2024,143,Zimbabwe,3.396,3.509,3.283,0.827,0.961,0.178,0.598,0.065,0.131,0.636
1918,2024,144,Malawi,3.260,3.390,3.130,0.588,0.489,0.280,0.677,0.115,0.136,0.975
1931,2024,145,Lebanon,3.188,3.277,3.098,1.223,0.984,0.440,0.279,0.071,0.041,0.150
1943,2024,146,Sierra Leone,2.998,3.102,2.894,0.786,0.692,0.327,0.613,0.138,0.052,0.391
1956,2024,147,Afghanistan,1.364,1.427,1.301,0.649,0.000,0.155,0.000,0.075,0.135,0.348

In [18]:
whr_24.columns

Index(['Year', 'Rank', 'Country name', 'Ladder score', 'upperwhisker',
       'lowerwhisker', 'Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [ ]:
whr_24 = whr_24[['Country name','Rank','Year','Explained by: Log GDP per capita',
       'Explained by: Social support', 'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual']].copy()

whr_24

,Country name,Rank,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,1,1.749,1.783,0.824,0.986,0.110,0.502,1.782
13,Denmark,2,1.825,1.748,0.820,0.955,0.150,0.488,1.535
26,Iceland,3,1.799,1.840,0.873,0.971,0.201,0.173,1.659
45,Sweden,4,1.783,1.698,0.889,0.952,0.170,0.467,1.385
58,Netherlands,5,1.822,1.667,0.844,0.860,0.186,0.344,1.583
...,...,...,...,...,...,...,...,...,...
1905,Zimbabwe,143,0.827,0.961,0.178,0.598,0.065,0.131,0.636
1918,Malawi,144,0.588,0.489,0.280,0.677,0.115,0.136,0.975
1931,Lebanon,145,1.223,0.984,0.440,0.279,0.071,0.041,0.150
1943,Sierra Leone,146,0.786,0.692,0.327,0.613,0.138,0.052,0.391
1956,Afghanistan,147,0.649,0.000,0.155,0.000,0.075,0.135,0.348

In [20]:
# melt. index cols are 'Counrty name' and 'Rank'
whr_24 = pd.melt(whr_24, id_vars=['Country name','Rank'], var_name='Factor', value_name='Score')

whr_24

      Country name  Rank                            Factor  Score
0          Finland     1  Explained by: Log GDP per capita  1.749
1          Denmark     2  Explained by: Log GDP per capita  1.825
2          Iceland     3  Explained by: Log GDP per capita  1.799
3           Sweden     4  Explained by: Log GDP per capita  1.783
4      Netherlands     5  Explained by: Log GDP per capita  1.822
...            ...   ...                               ...    ...
1024      Zimbabwe   143               Dystopia + residual  0.636
1025        Malawi   144               Dystopia + residual  0.975
1026       Lebanon   145               Dystopia + residual  0.150
1027  Sierra Leone   146               Dystopia + residual  0.391
1028   Afghanistan   147               Dystopia + residual  0.348

[1029 rows x 4 columns]

In [22]:
# create a separate df with top 10 and bottom 10
whr_24_top = whr_24[whr_24['Rank'] <= 10].copy()

whr_24_bottom = whr_24[whr_24['Rank'] >= 138].copy()

In [25]:
# add a column to indicate top or bottom
whr_24_top['Top/Bottom'] = 'Top 10'
whr_24_bottom['Top/Bottom'] = 'Bottom 10'
# concatenate top and bottom
whr_24_combined = pd.concat([whr_24_top, whr_24_bottom], ignore_index=True)


whr_24_combined

     Country name  Rank                            Factor  Score Top/Bottom
0         Finland     1  Explained by: Log GDP per capita  1.749     Top 10
1         Denmark     2  Explained by: Log GDP per capita  1.825     Top 10
2         Iceland     3  Explained by: Log GDP per capita  1.799     Top 10
3          Sweden     4  Explained by: Log GDP per capita  1.783     Top 10
4     Netherlands     5  Explained by: Log GDP per capita  1.822     Top 10
..            ...   ...                               ...    ...        ...
135      Zimbabwe   143               Dystopia + residual  0.636  Bottom 10
136        Malawi   144               Dystopia + residual  0.975  Bottom 10
137       Lebanon   145               Dystopia + residual  0.150  Bottom 10
138  Sierra Leone   146               Dystopia + residual  0.391  Bottom 10
139   Afghanistan   147               Dystopia + residual  0.348  Bottom 10

[140 rows x 5 columns]

In [26]:
whr_24_combined.to_csv('whr.csv', index=False)